[options]
    bootstrap_before = 'custom#before'
    bootstrap_after = 'custom#after'

    colorscheme = "dracula"
    enable_guicolors = true

    # 0: 1 -> ➊
    # 1: 1 -> ➀
    # 2: 1 -> ⓵
    # 3: 1 -> ¹
    # 4: 1 -> 1
    buffer_index_type = 4
    windows_index_type = 4

    enable_tabline_filetype_icon = false

    enable_statusline_mode = true
    statusline_separator = 'arrow'

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
    ]

    # disable cursor blinking
    terminal_cursor_shape = 1

[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[custom_plugins]]
    repo = "https://github.com/Mofiqul/dracula.nvim"
    merged = false
