[options]
    colorscheme = "dracula"
    colorscheme_bg = "dark"

    enable_guicolors = true
    buffer_index_type = 4
    enable_tabline_filetype_icon = true

    enable_statusline_mode = false

[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"
