[options]
    colorscheme = "dracula"
    enable_guicolors = true

    # 0: 1 -> ➊
    # 1: 1 -> ➀
    # 2: 1 -> ⓵
    # 3: 1 -> ¹
    # 4: 1 -> 1
    buffer_index_type = 4

    enable_tabline_filetype_icon = false

    enable_statusline_mode = true

    statusline_separator = 'arrow'

[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "colorscheme"
